### ISSUE TITLE
Question about internal implementation

### ISSUE THREAD

**Issue by Orxcle-xx** [ValvePython/steam#172]
Hi,

I just wanted to confirm that this library is based on official API / SDK ( "Steamworks" / https://partner.steamgames.com/doc/api ) and hence it's OK to use.

Otherwise ( if this library ) is created by reverse engineering of the Steam, when it could be dangerous to use as it can become broken at any point when Steam will update their client.

Thank you in advance.
Best Regards

**Comment by Orxcle-xx** [comment]
Hi,

Thanks for you reply. I understand that it could be a bit off topic but could you briefly explain the difference between SteamKit and Steamworks SDK?

Is SteamKit an official API / SDK from Valve?

Best regards

**Comment by rossengeorgiev** [comment]
The SDK is used to integrate games with Steam. It could potentially be used for automation. SteamKit is a result reverse engineering the Steam client and be used for any interactions with the Steam platform, not limited by the APIs exposed by the SDK. It has further resulted in various ports, such as this one, and other. These libraries can be used to build web applications with features that would be otherwise impossible.

**Comment by Orxcle-xx** [comment]
OK, thank you.

Forget me for digging it even further, but are you sure that Steamworks SDK can help for automation of others game? ie can I use Steamworks to automate lobby creation of Dota?

**Comment by rossengeorgiev** [comment]
Unlikely. There are number of dota related libraries that can already do this and are used across multiple web services. Ultimately, something like that is not officially supported, hence why these libraries exist.

**Comment by Orxcle-xx** [comment]
OK. Thank you for the help.
