### ISSUE TITLE
Add param to cli_login to denote as headless

### ISSUE THREAD

**Issue by csm10495** [ValvePython/steam#306]
https://github.com/ValvePython/steam/blob/05ff121c0afba8d5130d0a5630742f24869ba0ff/steam/client/__init__.py#L624

Requesting we add a headless=False parameter (or similar) to cli_login() a few days ago steam was down for a few moments and my code attempted to login. It was stuck on a 

```
Steam is down. Keep retrying? [y/n]: 
```

prompt. I'd rather it raise an exception in this case since I wasn't there to press y/n. An exception would have been noted upstream in my code and it would have tried again later.

**Comment by rossengeorgiev** [comment]
The idea behind `cli_login()` is convenience for interactive cli scripts. It's interactive by design. Not sure `headless` makes sense. What happens when it has to prompt, just return? Then the code on the next level would need to check the return, which `cli_login()` already does once. Duplication. I suppose the "Steam is down" prompt is special case, but it could be a prompt for 2FA or email code.

Sounds like you are using your program non-interactively, so the best approach is to implement the login logic in way that suites that.

**Comment by csm10495** [comment]
My thought was that if it were to prompt, raise an exception to not wait forever. Though if by design we don't want this function called via an automated workflow, I could just call `.login(...)` and manually `reconnect()` if needed.

Different idea, can we add `prompt_for_unavailable` as a param and default it to True, so I can just set it to False? I think that would have led to it retrying.

**Comment by rossengeorgiev** [comment]
The problem there is that you end up in a endless loop if you cant reconnect to steam. The more reasonable behavior is to return and let the application decide. Let's say we do that, then you can still get stuck on prompt for code. To me this seems to be solving the wrong problem. 

If you need a custom flow, you implement it `login()`, just as `cli_login()` does. In this case, just copy `cli_login()` and overload it in your own class, and remove the lines you don't like.

```python
class MySteamClient(SteamClient):
  def cli_login(.....)
     ...

client = MySteamClient()
```

**Comment by csm10495** [comment]
Fair enough. I didn't really want to copy paste the whole function to remove a line or 2 but alright. Thanks anyways.
